import config from "@/config.js";

export default [
  {
    title: "compose-intro-showcase",
    description:
      "Highlight different features of the app using Jetpack Compose",
    tags: [
      `android`,
      `kotlin`,
      `material-design`,
      `kotlin-library`,
      `showcase`,
      `android-library`,
      `android-development`,
      `jetpack`,
      `intro`,
      `feature`,
      `jetpack-android`,
      `app-intro`,
      `jetpack-compose`,
      `jetpack-compose-tutorial`,
    ],
    link: "https://github.com/canopas/compose-intro-showcase",
    stars: config.INTRO_SHOWCASE_STARS,
    forks: "32",
    color: "#A97BFF",
    language: "Kotlin",
  },
  {
    title: "UIPilot",
    description: "The missing typesafe SwiftUI navigation library",
    tags: [
      `macos`,
      `swift`,
      `ios`,
      `router`,
      `xcode`,
      `navigation`,
      `routing`,
      `ios-ui`,
      `navigation-view`,
      `swiftui`,
      `swift5`,
    ],
    link: "https://github.com/canopas/UIPilot",
    stars: config.UIPILOT_STARS,
    forks: "25",
    color: "#F05138",
    language: "Swift",
  },
  {
    title: "Jetpack Compose animations",
    description: "Cool animations implemented with Jetpack compose",
    tags: [],
    link: "https://github.com/canopas/compose-animations-examples",
    stars: config.JETPACK_COMPOSE_ANIMATION_STARS,
    forks: "35",
    color: "#A97BFF",
    language: "Kotlin",
  },
  {
    title: "Swiftui-animations-examples",
    description: "Cool animations implemented with SwiftUI.",
    tags: [],
    link: "https://github.com/canopas/swiftui-animations-examples",
    stars: config.SWIFT_UI_ANIMATION_STARS,
    forks: "3",
    color: "#F05138",
    language: "Swift",
  },
  {
    title: "Tailwind Animations Examples",
    description: "Cool animations implemented with tailwindcss.",
    tags: [
      `css`,
      `vuejs`,
      `animations`,
      `animation-css`,
      `tailwind`,
      `tailwindcss`,
      `tailwind-elements`,
      `tailwind-animations`,
      `animation-example`,
      `tailwindcss-animate`,
      `tailwind-animations-examples`,
      `animation-examples`,
    ],
    link: "https://github.com/canopas/tailwind-animations-examples",
    stars: config.TAILWIND_ANIMATIONS_STARS,
    forks: "6",
    color: "#F1E05A",
    language: "JavaScript",
  },
  {
    title: "ComposeRecyclerView",
    description:
      "Seamlessly integrate Jetpack Compose composables in RecyclerView with ComposeRecyclerView🔥. This library enhances performance⚡, tackles LazyList issues🔨, and offers built-in drag-and-drop👨🏽‍💻 support for dynamic UIs.",
    tags: [
      `kotlin`,
      `android`,
      `drag-and-drop`,
      `recyclerview`,
      `kotlin-library`,
      `android-library`,
      `recyclerview-adapter`,
      `draggable`,
      `composer-library`,
      `lazylist`,
      `jetpack-compose`,
      `jetpack-compose-tutorial`,
      `compose-ui`,
    ],
    link: "https://github.com/canopas/compose-recyclerview",
    stars: config.COMPOSE_RECYCLEVIEW_STARS,
    forks: "7",
    color: "#A97BFF",
    language: "Kotlin",
  },
  {
    title: "Canopas - Blog",
    description: "Feature-Rich blogs platform built with strapi and next.js",
    tags: [
      `website`,
      `development`,
      `web-development`,
      `web`,
      `responsive`,
      `reactjs`,
      `nextjs`,
    ],
    link: "https://github.com/canopas/canopas-blog",
    stars: config.CANOPAS_BLOG_WEBSITE_STARS,
    forks: "9",
    color: "#F1E05A",
    language: "JavaScript",
  },
  {
    title: "Canopas - website",
    description:
      "Responsive website built with Vue.js and vite by following best practices.",
    tags: [
      `golang`,
      `aws`,
      `website`,
      `boilerplate`,
      `development`,
      `vuejs`,
      `web-development`,
    ],
    link: "https://github.com/canopas/canopas-website",
    stars: config.CANOPAS_WEBSITE_STARS,
    forks: "4",
    color: "#41B883",
    language: "Vue",
  },
  {
    title: "RichEditorSwiftUI",
    description:
      "RichEditorSwiftUI is swift based library, it is made to make rich text editing easy with SwiftUI.",
    tags: [
      `editor`,
      `swift`,
      `string`,
      `uikit`,
      `rich-text-editor`,
      `richtext`,
      `swiftui`,
    ],
    link: "https://github.com/canopas/rich-editor-swiftui",
    stars: config.RICHEDITOR_SWIFTUI_STARS,
    forks: "2",
    color: "#F05138",
    language: "Swift",
  },
  {
    title: "RichEditor",
    description: "Android WYSIWYG Rich editor for Jetpack compose.",
    tags: [],
    link: "https://github.com/canopas/rich-editor-compose",
    stars: config.RICHEDITOR_STARS,
    forks: "0",
    color: "#A97BFF",
    language: "Kotlin",
  },
];
