AWSTemplateFormatVersion: "2010-09-09"
Transform:
  - AWS::LanguageExtensions
  - AWS::Serverless-2016-10-31

Description: Canopas website serverless deployment with SSR.

Parameters:
  EnvName:
    Type: String
    Description: Name of an environment.
    AllowedPattern: ^.*[^0-9]$
    ConstraintDescription: Must end with non-numeric character.
    AllowedValues:
      - dev
      - prod
  ZipFileName:
    Type: String
    Description: Name of the zip file.

Conditions:
   IsDev: 
      Fn::Equals: 
        - Fn::Sub: ${EnvName}
        - dev

Resources:
  SSRFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Zip
      CodeUri:
        Fn::Sub: s3://canopas-lambda-handlers/${ZipFileName}
      Handler: index.handler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      MemorySize: 256
      Timeout: 30
      FunctionName:
        Fn::Sub: canopas-website-ssr-frontend-${EnvName}
      Description:
        Fn::Sub: Canopas Website SSR Frontend Lambda ${EnvName}
      FunctionUrlConfig:
        AuthType: NONE
      Environment:
        Fn::If:
          - IsDev
          - Variables:
              NUXT_SITE_ENV: 
                Fn::Sub: ${EnvName}
          - Ref: AWS::NoValue 