name: Build
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3

      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17.5'

      - uses: actions/setup-node@v1
        with:
          node-version: '16'

      - name: Build frontend
        run: |
          cd vue-frontend
          npm ci
          npm run build

      - name: Build backend
        run: |
          GOOS=linux GOARCH=amd64 go build -o main main.go