name: DeployDevFrontend
on:
  push:
    branches:
      - master
      
jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3

      - uses: actions/setup-node@v1
        with:
          node-version: '16'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::569704406482:role/github-actions-s3-access
          aws-region: ap-south-1
      - name: Deploy cloudfront
        id: canopas-website-dev-frontend-stack
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: canopas-website-dev-frontend-stack
          template: infrastructure/template-frontend.yml
          capabilities: CAPABILITY_IAM,CAPABILITY_NAMED_IAM
          timeout-in-minutes: "10"
          no-fail-on-empty-changeset: "1"
          parameter-overrides: >-
            S3BucketName=dev-stack-canopas-v1-frontend
      - name: Build frontend
        run: |
          cd vue-frontend
          npm ci
          npm run build
      - name: Upload to S3
        run: |
          cd vue-frontend
          aws s3 sync --delete --cache-control 'max-age=31536000' --exclude *.html dist/ s3://dev-stack-canopas-v1-frontend/
          aws s3 sync --cache-control 'no-cache' dist/ s3://dev-stack-canopas-v1-frontend/