name: DeployDevFrontend
on:
  push:
    branches:
      - "master"
      
jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3

      - uses: actions/setup-node@v1
        with:
          node-version: "17"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-frontend-access
          aws-region: ap-south-1

      - name: Build frontend and push on ECR
        run: |
          cd vue-frontend
          sh ./../deploy/generate-sitemap.sh https://dev-stack.canopas.com https://dev-stack-api.canopas.com && cd ..
          sh ./deploy/deploy-ecr-image.sh dev ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.$AWS_REGION.amazonaws.com/canopas-website-ssr-app

      - name: Deploy cloudformation stack with cloudfront
        id: canopas-website-dev-frontend-stack-ECS
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: canopas-website-dev-frontend-stack-ECS
          template: infrastructure/template-frontend.yml
          capabilities: CAPABILITY_IAM,CAPABILITY_NAMED_IAM
          timeout-in-minutes: "10"
          no-fail-on-empty-changeset: "1"
          parameter-overrides: >-
            LoadBalancerName=CanopasWebsiteALB-dev,
            ClusterName=canopas-website-dev,
            TargetGroupName=canopas-website-tg-dev,
            SecurityGroupName=canopas-website-alb-sg-dev,
            SecurityGroupContainerName=canopas-website-alb-to-farget-dev,
            ImageTag=${{ github.sha }}-dev
